### ISSUE TITLE
Provide documentation on how to show the recent set of releases

### ISSUE THREAD

**Issue by jverkoey** [mergesort/Recap#9]
As mentioned in https://www.threads.net/@davidrepola/post/DBJv_mgyHUz, it would be nice to be able to easily find old release notes within the app. I suspect this is possible to do with Recap's APIs as-is, but the documentation doesn't provide a clear example of how to do this so I'm filing this issue to track the idea while I dig in to how it could be accomplished.

**Comment by jverkoey** [comment]
Oh! I just realized that the `RecapScreen` already shows the full history of releases! So I suppose it's just a matter of making it possible to re-open the sheet?

**Comment by mergesort** [comment]
@jverkoey There aren't any restrictions on when or how you present a sheet, since Recap only provides a View. If you take a peek at the [demo app](https://github.com/mergesort/Recap/tree/main/Demo) you'll see that the sheet presents on app launch, but if you dismiss the screen there's a button you can press to re-present the screen.

Since Recap doesn't have any opinion on how screens should or shouldn't be presented, I didn't think it was something I should document, but do you think I should add some to make this clearer?

**Comment by jverkoey** [comment]
Ah! Sorry I meant to close this but lost it today. Agreed that docs probably aren't needed here :)
